os:
  - linux
services:
  - docker
language: node_js
node_js:
  - "12.16.1"

#Configured according to https://docs.travis-ci.com/user/sonarcloud/
addons:
  sonarcloud:
    organization: "2020-2021-ecom-info5-g04"

script:
  - cd uwind
  - chmod +x mvnw
    #The following command builds project, prepares JaCoCo, initializes Sonar, runs the tests with "verify" and then executes the SonarCloud analysis
    #Using JaCoCo because multiple maven commands
    #We choose to connect thanks to a Travis environment variable, SONAR_TOKEN
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent initialize sonar:sonar verify sonar:sonar -Pcoverage -Dsonar.projectKey=2020-2021-ECOM-INFO5-G04_Sandbox -Dsonar.login=${SONAR_TOKEN}

#https://docs.travis-ci.com/user/deployment/azure-web-apps/